---
- name: Deploy CosmosDB for View Counter
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group: cloud-resume-challenge
    location: eastus
    storage_account_name: andrewbrowncrc2025
    bicep_file: "{{ playbook_dir }}/../db.bicep"
    built_json: "{{ playbook_dir }}/../db.built.json"
    deployment_name: "db-deploy"
    cosmosdb_account_name: "crcviewcounter5293"

  tasks:
    - name: Verify Azure CLI login
      ansible.builtin.command: az account show
      changed_when: false

    - name: Ensure resource group exists
      ansible.builtin.command: >
        az group create
        --name {{ resource_group }}
        --location {{ location }}
        --output none
      changed_when: false

    - name: Compile storage.bicep -> JSON
      ansible.builtin.command: >
        az bicep build
        --file {{ bicep_file }}
        --outfile {{ built_json }}
      changed_when: true

    - name: Validate template (storage)
      ansible.builtin.command: >
        az deployment group validate
        --resource-group {{ resource_group }}
        --template-file {{ built_json }}
        --parameters location={{ location }} cosmosdb_account_name={{ cosmosdb_account_name }}
        --output json
      changed_when: false

    - name: Deploy cosmosdb
      ansible.builtin.command: >
        az deployment group create
        --resource-group {{ resource_group }}
        --name {{ deployment_name }}
        --template-file {{ built_json }}
        --parameters location={{ location }} cosmosdb_account_name={{ cosmosdb_account_name }}
        --output json
      register: storage_deploy
      changed_when: storage_deploy.rc == 0