---
- name: Deploy GCS static site bucket via Terraform
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vaults/prod.yml
  vars:
    project_path: "{{ playbook_dir }}/../"
    tf_vars_file: "{{ project_path }}/terraform.tfvars"   # optional

  tasks:
    - name: Create temp file for GCP service account key
      ansible.builtin.tempfile:
        state: file
        suffix: .json
      register: sa_key_tmp
    - name: Write GCP service account key to temp file
      ansible.builtin.copy:
        dest: "{{ sa_key_tmp.path }}"
        content: "{{ gcp_sa_key_json }}"
        mode: '0600'
    - name: Terraform init/plan/apply
      community.general.terraform:
        project_path: "{{ project_path }}"
        force_init: true
        state: present
        variables: "{{ {'bucket_name': bucket_name} if (bucket_name is defined) else omit }}"
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ sa_key_tmp.path }}"
        TF_TOKEN_app_terraform_io: "{{ tfc_token }}"
      register: tf_apply
    - name: Show Terraform output (if any)
      ansible.builtin.debug:
        var: tf_apply